# Cloudflare Pages Build Configuration

[build]
command = "npm run build:cf-pages"
publish = "dist"

# Node version for build
[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

# Functions directory for Cloudflare Pages Functions (if using API routes)
[functions]
directory = "functions"

# Security headers for all routes
[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.openai.com https://*.workers.dev;"

# Cache headers for static assets
[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
for = "*.js"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
for = "*.css"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# API proxy to Cloudflare Worker (update to your deployed worker URL)
[[redirects]]
from = "/api/*"
to = "https://nphies-healthcare-worker.<your-cloudflare-account>.workers.dev/:splat"
status = 200
force = true

# SPA fallback for client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200